title = "Finding the Planets"
author = "Daan van Berkel"
description = "A book accompanying a workshop to find the planets around Trappist-1."

[output.html]
destination = "../docs/"
mathjax-support = true